### ISSUE TITLE
Ideen warum das Menü manchmal kommt

### ISSUE THREAD

**Issue by adrianhoppe** [matthiasplappert/lego-mindstorm#54]
Warum kommt das Menü manchmal?
--> Standard State ist vielleicht der Idle State? (Eigentlich nicht)
--> ShutDownBehaviour hat höchste Priorität, evtl. wird hier der ExitState gesetzt (eher unwahrscheinlich)

**Comment by adrianhoppe** [comment]
Kann es vorkommen, dass keine der takeControl() Methoden true zurück gibt?
(außer natürlich wenn der ExitState gesetzt ist)

**Comment by christianolms** [comment]
Solange es zum Default-State eine Behaviour gibt sollte diese takeControl true zurückgeben. 
Falls keine takeControl aktiviert wird passiert folgendes:

" Parameter: boolean returnWhenInacative; If true, the program exits when there is no behavior that wants to take control. Otherwise, the program runs until shut down by pressing the Enter and Escape buttons. "
Arbitrator beschreibung auf : http://www.lejos.org/nxt/nxj/tutorial/Behaviors/BehaviorProgramming.htm
